let ads = `###A9AdsMiddleBoxTop
###A9AdsOutOfStockWidgetTop
###A9AdsServicesWidgetTop
###AD-300x250
###AD-300x250-1
###AD-300x250-2
###AD-300x250-3
###AD-HOME-LEFT
###AD001
###AD1line
###AD2line
###AD300Right
###AD300_VAN
###AD300x250
###AD300x600
###AD728Top
###ADEXPERT_PUSHDOWN
###ADEXPERT_RECTANGLE
###ADInterest
###ADNETwallBanner1
###ADNETwallBanner2
###ADSLOT_1
###ADSLOT_2
###ADSLOT_3
###ADSLOT_4
###ADSLOT_SKYSCRAPER
###ADSPACE02
###ADSPACE03
###ADSPACE04
###ADS_2
###ADSlideshow
###ADSpro
###ADV120x90
###ADVERTISE_HERE_ROW
###ADVERTISE_RECTANGLE1
###ADVERTISE_RECTANGLE2
###ADVTG_CONTAINER_pushdown
###ADVTLEFT1
###ADVTLEFT2
###ADVTRIGHT1
###ADV_VIDEOBOX_2_CNT
###ADVleaderboard
###AD_160
###AD_300
###AD_468x60
###AD_C
###AD_CONTROL_13
###AD_CONTROL_22
###AD_CONTROL_28
###AD_CONTROL_29
###AD_CONTROL_8
###AD_G
###AD_L
###AD_ROW
###AD_Top
###AD_Zone
###AD_banner
###AD_banner_bottom
###AD_gallery
###AD_google
###AD_half
###AD_newsblock
###AD_rectangle
###AD_rr_a
###AD_text
###ADback
###ADbox
###ADgoogle_newsblock
###ADoverThePlayer
###ADsmallWrapper
###AFF_popup
###APC_ads_details
###AUI_A9AdsMiddleBoxTop
###AUI_A9AdsWidgetAdsWrapper
###Ad-0-0-Slider
###Ad-0-1-Slider
###Ad-1-0-Slider
###Ad-1-1-Slider
###Ad-1-2-Slider
###Ad-3-Slider
###Ad-4-Slider
###Ad-5-2-Slider
###Ad-8-0-Slider
###Ad-9-0-Slider
###Ad-Container
###Ad-Top
###Ad160x600
###Ad160x600_0_adchoice
###Ad300x145
###Ad300x250
###Ad300x250_0
###Ad300x600_0_adchoice
###Ad3Left
###Ad3Right
###Ad3TextAd
###Ad728x90
###Ad990
###AdAboveGame
###AdArea
###AdAreaH
###AdAuth1
###AdAuth2
###AdAuth3
###AdAuth4
###AdBanner
###AdBannerSmallContainer
###AdBanner_F1
###AdBanner_S
###AdBar
###AdBar1
###AdBigBox
###AdBlock
###AdBlockBottomSponsor
###AdBottomLeader
###AdBottomRight
###AdBox160
###AdBox2
###AdBox300
###AdBox728
###AdBoxMoreGames
###AdButtons
###AdColumn
###AdContainer
###AdContainerTop
###AdContentModule_F
###AdContent_0_0_pnlDiv
###AdControl_TowerAd
###AdDetails_GoogleLinksBottom
###AdDetails_InsureWith
###AdDetails_SeeMoreLink
###AdDisclaimer
###AdDisplay_LongLink
###AdDisplay_TallLink
###AdDiv
###AdExtraBlock
###AdFeedbackLinkID_lnkItem
###AdFoxDiv
###AdFrame1
###AdFrame2
###AdFrame4
###AdHeader
###AdHouseRectangle
###AdImage
###AdIndexTower
###AdLayer1
###AdLayer2
###AdLeaderboard2RunofSite
###AdLeaderboardBottom
###AdLeaderboardTop
###AdLocationMarketPage
###AdMPUHome
###AdMediumRectangle1300x250
###AdMediumRectangle2300x250
###AdMediumRectangle3300x250
###AdMiddle
###AdMobileLink
###AdPanel
###AdPanelBigBox
###AdPanelLogo
###AdPopUp
###AdPubsPromo
###AdRectangle
###AdRectangleBanner
###AdSense-Skyscraper
###AdSense1
###AdSense2
###AdSense3
###AdSenseBottomAds
###AdSenseDiv
###AdSenseMiddleAds
###AdSenseResults1_adSenseSponsorDiv
###AdSenseTopAds
###AdServer
###AdShopSearch
###AdShowcase
###AdShowcase_F
###AdShowcase_F1
###AdSky23
###AdSkyscraper
###AdSlot_AF-Right-Multi
###AdSpaceLeaderboard
###AdSpacing
###AdSponsor_SF
###AdSpotMovie
###AdSquare02
###AdSubsectionShowcase_F1
###AdTaily_Widget_Container
###AdTargetControl1_iframe
###AdTop
###AdTopBlock
###AdTopLeader
###AdTrackVideoPlayer
###AdWidgetContainer
###AdZone1
###AdZone2
###Ad_976x105
###Ad_BelowContent
###Ad_Block
###Ad_Center1
###Ad_Premier
###Ad_Right1
###Ad_RightBottom
###Ad_RightTop
###Ad_TopLeaderboard
###Adbanner
###Adc1_AdContainer
###Adc2_AdContainer
###Adc3_AdContainer
###AdcBB_AdContainer
###Adcode
###Adlabel
###Adrectangle
###Ads-C
###Ads-D-728x90-hori
###Ads270x510-left
###Ads470by50
###AdsBannerTop
###AdsBottomContainer
###AdsBottomIframe
###AdsCarouselBoxArea
###AdsContainerTop
###AdsContent
###AdsContent_SearchShortRecB_UPSSR
###AdsDiv
###AdsFrame
###AdsHome2
###AdsLeader
###AdsLeft_1
###AdsPlayRight_1
###AdsRight
###AdsShowCase
###AdsTopContainer
###AdsVideo250
###AdsWrap
###Ads_BA_BUT_box
###Ads_BA_CAD
###Ads_BA_CAD2
###Ads_BA_CAD2_Text
###Ads_BA_CAD_box
###Ads_BA_FLB
###Ads_BA_SKY
###Ads_CAD
###Ads_OV_BS
###Ads_Special
###Ads_TFM_BS
###Ads_google_01
###Ads_google_02
###Ads_google_03
###Ads_google_04
###Ads_google_05
###Adsense300x250
###AdsenseBottom
###AdsenseTop
###Adtag300x250Bottom
###Adtag300x250Top
###Adv-div
###Adv10
###Adv11
###Adv8
###Adv9
###AdvArea
###AdvBody
###AdvContainer
###AdvContainerBottom
###AdvContainerMidCenter
###AdvContainerMiddleRight
###AdvContainerTopCenter
###AdvContainerTopRight
###AdvFooter
###AdvFrame1
###AdvHead
###AdvHeader
###Adv_Footer
###Adv_Main_content
###Adv_Maxi_Leaderboard_A
###Adv_Maxi_Leaderboard_B
###Adv_Superbox_A
###Adv_Superbox_B
###Adv_Superbox_C
###Adv_Superbox_D
###Advert1
###AdvertMPU23b
###AdvertPanel
###AdvertText
###AdvertiseFrame
###Advertisement1
###Advertisement2
###AdvertisementRightColumnRectangle
###Advertisements
###AdvertisingDiv_0
###AdvertisingLeaderboard
###AdvertismentHomeTopRight
###Advertorial
###Advertorials
###AdvertsBottom
###AdvertsBottomR
###Adverts_AdDetailsBottom_300x600
###Adverts_AdDetailsMiddle_300x250
###ArticleBottomAd
###BANNER_160x600
###BANNER_300x250
###BANNER_728x90
###BB1-ad
###BBCPH_MCPH_MCPH_P_ArticleAd1
###BBCPH_MCPH_MCPH_P_OasAdControl1Panel
###BBCPH_MCPH_MCPH_P_OasAdControl2Panel
###BBCPH_MCPH_MCPH_SponsoredLinks1
###BBoxAd
###BDV_fullAd
###BackgroundAdContainer
###Banner300x250Module
###Banner728x90
###BannerAd
###BannerAds
###BannerAdvert
###BannerAdvertisement
###BannerXGroup
###BelowFoldAds
###BigBoxAd
###BigboxAdUnit
###BillBoardAdd
###BodyAd
###BodyTopAds
###Body_Ad8_divAdd
###BotAd
###Bottom468x60AD
###BottomAd0
###BottomAdContainer
###BottomAdSpacer
###BottomAds
###BottomPageAds
###BottomRightAdWrapper
###BrokerBox-AdContainer
###ButtonAd
###CONTENTAD
###CSpromo120x90
###ClickPop_LayerPop_Container
###ClickStory_ViewAD1
###ClickStory_ViewRightAD2
###Col2-1-ComboAd-Proxy
###CommonHeaderAd
###CompanyDetailsNarrowGoogleAdsPresentationControl
###CompanyDetailsWideGoogleAdsPresentationControl
###ContentAd
###ContentAd1
###ContentAd2
###ContentAdPlaceHolder1
###ContentAdPlaceHolder2
###ContentAdView
###ContentAdXXL
###ContentAdtagRectangle
###ContentPlaceHolder1_adds
###ContentPlaceHolder1_advertControl1_advertLink
###ContentPlaceHolder1_advertControl3_advertLink
###ContentPlaceHolder1_pnlGoogleAds
###ContentPolepositionAds_Result
###Content_CA_AD_0_BC
###Content_CA_AD_1_BC
###ConversationDivAd
###CornerAd
###CountdownAdvert
###DARTad300x250
###DEFAULT_ADV4_SWF
###DFM-adPos-bottomline
###DFPAD_MR
###DFP_in_article_mpu
###DFP_top_leaderboard
###DartAd300x250
###DartAd990x90
###DealsPageSideAd
###DivAd
###DivAd1
###DivAd2
###DivAd3
###DivAdA
###DivAdB
###DivAdC
###DivAdEggHeadCafeTopBanner
###DivAdForumSplitBottom
###DivMsnCamara
###DivTopAd
###DividerAd
###DynamicAD
###FFN_imBox_Container
###FIN_300_250_position2_ad
###FIN_300_x_250_600_position2_ad
###FIN_300x250_pos1_ad
###FIN_300x80_facebook_ad
###FIN_468x60_sponsor_ad
###FIN_640x60_promo_ad
###FIN_728_90_leaderboard_ad
###FIN_ad_300x100_pos_1
###FIN_videoplayer_300x250ad
###FRONTADVT2
###FRONTADVT3
###FRONTADVT4
###FRONTADVT5
###FRONTADVT8
###FooterAd
###FooterAdBlock
###FooterAdContainer
###ForumSponsorBanner
###Freeforums-AdS-footer-728x90
###Freeforums-AdS-header-728x90
###FrontPageRectangleAd
###GOOGLEADS_BOT
###GOOGLEADS_CENTER
###GOOGLE_ADS_13
###GOOGLE_ADS_151
###GOOGLE_ADS_16
###GOOGLE_ADS_2
###GOOGLE_ADS_49
###GOOGLE_ADS_56
###GOOGLE_ADS_94
###GameMediumRectangleAD
###GamePageAdDiv
###GoogleADsense
###GoogleADthree
###GoogleAd
###GoogleAd1
###GoogleAd2
###GoogleAd3
###GoogleAdExploreMF
###GoogleAdRight
###GoogleAdTop
###GoogleAds250X200
###GoogleAdsPlaceHolder
###GoogleAdsPresentationControl
###GoogleAdsense
###GoogleAdsenseMerlinWrapper
###GoogleLeaderBoardAdUnit
###GoogleLeaderBoardAdUnitSeperator
###GoogleRelatedAds
###GoogleSponsored
###Google_Adsense_Main
###HALExchangeAds
###HALHouseAd
###HB_News-ad
###HEADERAD
###HOME_TOP_RIGHT_BOXAD
###HP_adUnits
###H_Ad_728x90
###H_Ad_Wrap
###HeaderAD
###HeaderAd
###HeaderAdBlock
###HeaderAdSidebar
###HeaderAdsBlock
###HeaderAdsBlockFront
###HeaderBannerAdSpacer
###HeaderTextAd
###HeroAd
###HomeAd1
###HomeBannerAd
###Home_AdSpan
###HomepageAdSpace
###HorizontalAd
###HouseAd
###HouseAdInsert
###IC1-ad
###IC2-ad
###ID_Ad_Sky
###IM_AD
###IN_HOUSE_AD_SWITCHER_0
###IframeAdBannerSmallContainer
###ImageAdSideColumn
###ImageRotaAreaAD
###InterstitialAD_0_1ckp
###IslandAd_DeferredAdSpacediv
###JobsearchResultsAds
###Journal_Ad_125
###Journal_Ad_300
###JuxtapozAds
###KH-contentAd
###LB_Row_Ad
###LM_ad_unit
###LS-google-ad
###LargeRectangleAd
###LeaderTop-ad
###LeaderboardAdvertising
###LeaderboardNav_ad_placeholder
###LeftAd
###LeftAd1
###LeftAdF1
###LeftAdF2
###LeftSideBarAD
###LftAd
###LittleAdvert
###LoungeAdsDiv
###LovelabAdoftheDay
###LowerContentAd
###MAINAD-box
###MPUAdSpace
###MPUadvertising
###MPUadvertisingDetail
###M_AD
###MainAd
###MainAd1
###MainContent_ucTopRightAdvert
###MainHeader1_FRONTADVT10
###MainHeader1_FRONTADVT11
###MainRightStrip1_RIGHTADVT2
###MainRightStrip1_RIGHTADVT3
###MainRightStrip1_RIGHTADVT4
###MainRightStrip1_RIGHTADVT5
###MainSponsoredLinks
###MastheadAd
###MediumRectangleAD
###Meebo\:AdElement\.Root
###MidPageAds
###MiddleRightRadvertisement
###Module-From_Advertisers
###MyAdHeader
###MyAdSky
###MyAdsId
###NavAD
###Nightly_adContainer
###NormalAdModule
###OAS2
###OASMiddleAd
###OASRightAd
###OAS_AD_TOPRIGHT
###OAS_Top
###OAS_posBottom
###OAS_posRight
###OAS_posTopRight
###OpenXAds
###OverrideAdArea
###PPX_imBox_Container
###PREFOOTER_LEFT_BOXAD
###PREFOOTER_RIGHT_BOXAD
###PageLeaderAd
###PaneAdvertisingContainer
###PartialYahooJSAds-bottom-ads
###PartialYahooJSAds-top-ads
###PhotoAd1
###PostSponsorshipContainer
###PreRollAd
###PushDownAd
###RHS2Adslot
###RadAdSkyscraper
###RadAd_Skyscraper
###RelevantAds
###RgtAd1
###RhsIsland_DeferredAdSpacediv
###RightAd
###RightAdBlock
###RightAdSpace
###RightAdvertisement
###RightBottom300x250AD
###RightColumn125x125AD
###RightColumnAdContainer
###RightColumnSkyScraperAD
###RightNavTopAdSpot
###RightRailSponsor
###RightSponsoredAd
###RollOutAd970x66
###RollOutAd970x66iframe
###SBAArticle
###SBABottom
###SBAInHouse
###SBATier1
###SBATier2
###SBATier3
###SE20-ad-container
###SE_ADLINK_LAY_gd
###SIDEMENUAD
###SIM_ad_300x100_homepage_pos1
###SIM_ad_300x250-600_pos1
###SIM_ad_300x250_pos2
###SIM_ad_468x60_homepage_pos1
###SIM_ad_468x60_homepage_pos2
###SIM_ad_468x60_homepage_pos3
###SIM_ad_728x90_bottom
###SRPadsContainer
###ScoreboardAd
###SearchAd_PlaceHolder
###SearchAdsBottom
###SearchAdsTop
###Section-Ads
###SectionAd300-250
###SectionSponsorAd
###ServerAd
###SideAdMpu
###SideBarAdWidget
###SideMpuAdBar
###SidebarAd
###SidebarAdContainer
###SitenavAdslot
###SkyAd
###SkyscraperAD
###SlideShow_adv
###SlideShow_adv2
###SpecialAds
###Spons-Link
###SponsorBarWrap
###SponsoredAd
###SponsoredAds
###SponsoredLinks
###SponsoredResultsTop
###SponsorsAds
###TDads
###TL_footer_advertisement
###TOPADS
###TOP_ADROW
###TOP_RIGHT_BOXAD
###TPVideoPlayerAd300x250
###Tadspacecbar
###Tadspacefoot
###Tadspacehead
###Tadspacemrec
###TextLinkAds
###ThemeSection_adbanner2
###ThemeSection_adbanner3
###ThreadAd
###TipTopAdSpace
###TitleAD
###Top-Ad-Container
###Top1AdWrapper
###Top468x60AD
###TopADs
###TopAd
###TopAd0
###TopAdBox
###TopAdContainer
###TopAdDiv
###TopAdPlacement
###TopAdPos
###TopAdTable
###TopAdvert
###TopBannerAd
###TopCenterAdUnit
###TopGoogleCustomAd
###TopRightRadvertisement
###TopSideAd
###TopTextAd
###VM-MPU-adspace
###VM-footer-adspace
###VM-footer-adwrap
###VM-header-adspace
###VM-header-adwrap
###VertAdBox
###VertAdBox0
###WNAd1
###WNAd103
###WNAd17
###WNAd20
###WNAd41
###WNAd43
###WNAd46
###WNAd47
###WNAd49
###WNAd52
###WNAd63
###WarningCodecBanner
###WelcomeAd
###WindowAdHolder
###WordFromSponsorAdvertisement
###XEadLeaderboard
###XEadSkyscraper
###YahooAdParentContainer
###YahooAdsContainer`

const splitedAds = ads.split(/\n/);
const adsObj = {};
// for(let i in splitedAds){
//     console.log(i)
// }
splitedAds.forEach((el, idx)=>{
    adsObj[`${el.slice(2)}`] = idx + 1;
})
console.log(JSON.parse(JSON.stringify(adsObj)));